select = ['ALL']
ignore = ['ANN', 'ARG', 'COM812', 'D10', 'D203']
exclude = [
    '{{context.__project_slug}}/data',
    '{{context.__project_slug}}/static',
]
line-length = 120
src = ['{{context.__project_slug}}']

[per-file-ignores]
'__init__.py' = ['F401']

[flake8-quotes]
inline-quotes = 'single'
multiline-quotes = 'single'

[pydocstyle]
convention = 'google'

[isort]
known-first-party = ['{{context.__project_slug}}']
known-third-party = ['nagare']
force-sort-within-sections = true

[format]
quote-style = 'single'
